version: '3'
services:
  influxdb:
    container_name: influxdb-pdu
    image: influxdb:latest
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - TZ=Asia/Jakarta
      - INFLUXDB_HTTP_FLUX_ENABLED="false"
      - INFLUXDB_REPORTING_DISABLED="false"
      - INFLUXDB_HTTP_AUTH_ENABLED="false"
      - INFLUXDB_MONITOR_STORE_ENABLED="false"
      - INFLUX_USERNAME=admin
      - INFLUX_PASSWORD=admin123
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_ENABLED="true"
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/db:/var/lib/influxdb/backup
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8086"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - pdu_network

  mosquitto:
    container_name: mosquitto-pdu
    image: eclipse-mosquitto
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - pdu_network

  nodered:
    container_name: nodered-pdu
    image: nodered/node-red
    restart: unless-stopped
    user: "0"
    environment:
      - TZ=Asia/Jakarta
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data
    networks:
      - pdu_network

networks:
  pdu_network:
    driver: bridge
